application: lifepadbox
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  
- url: /admin/
  script: handler/admin_dashboard.py
  login: admin
  secure: always

- url: /admin/entry/.*
  script: handler/admin_entry_single.py
  login: admin
  secure: always
  
- url: /admin/entries/.*
  script: handler/admin_entry_batch.py
  login: admin
  secure: always

- url: /admin/collection/
  script: handler/admin_collection.py
  login: admin
  secure: always

- url: /admin/settings/
  script: handler/admin_settings.py
  login: admin
  secure: always

- url: /admin/convert/
  script: handler/admin_convert.py
  login: admin
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /test.html
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static
  
inbound_services:
- mail

